---
- hosts: win
  gather_facts: true
  vars:
    region: us-west-2
  tasks:
    - name: create a file
      win_file:
         region: "{{ region }}"
         path: C:\Users
         state: touch
