---
- hosts: win
  gather_facts: true
  vars:
    region: us-west-2
  tasks:
    - name: create a file
      win_file:
         region: "{{ region }}"
         AWS_ACCESS_KEY_ID: "{{ access }}"
         AWS_SECRET_ACCESS_KEY: "{{ secret }}"
         path: C:\users
         state: touch

